### ISSUE TITLE
AttributeError: 'MRIDatasetMRBRAINS2018' object has no attribute 'affine'

### ISSUE THREAD

**Issue by Healingl** [black0017/MedicalZooPytorch#14]
when load processed data, there is a bug
```
        if load:
            ## load pre-generated data
            self.list = utils.load_list(self.save_name)
            return
     ...
        self.affine = img_loader.load_affine_matrix(list_reg_t1[0]) # it is a bug
```

**Comment by iliasprc** [comment]
Hello,
The param load=True uses presegmented patches from medical images that you have created when load=False. 
I think if you move the line ( self.affine=....)  above the if loop the code should work fine

**Comment by Healingl** [comment]
@iliasprc Okay, I have solved this problem, thank you!
